import * as THREE from 'three';
import {createRobot} from './robot-model.js';
import {createStations,mesh,box,cyl} from './station-models.js';
const $=s=>document.querySelector(s),state=window.portfolioState;
const hero=$('#robot-view'),preview=$('#control-preview'),stationView=$('#station-view');
let arm,station,frameId=0,last=0,clock=0,heroVisible=true,previewVisible=false,stationVisible=false,activeStation=0,quality=state.quality;
let frames=0,slow=0,stationAttempted=false;
function renderer(view,label){const r=new THREE.WebGLRenderer({alpha:true,antialias:quality==='high',powerPreference:'low-power'});r.setPixelRatio(Math.min(devicePixelRatio||1,quality==='lite'?1.15:2));r.toneMapping=THREE.ACESFilmicToneMapping;r.toneMappingExposure=1.25;r.shadowMap.enabled=quality==='high';r.shadowMap.type=THREE.PCFSoftShadowMap;r.domElement.setAttribute('role','img');r.domElement.setAttribute('aria-label',label);r.domElement.style.touchAction='pan-y';view.append(r.domElement);view.classList.add('scene-ready');r.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();view.classList.remove('scene-ready');r.setAnimationLoop(null);r.userLost=true;if(r===arm?.renderer){$('#machine-controls').disabled=true;$('#robot-state').textContent='3D paused. Reload to restore the interactive view.';}else $('#station-illustration').textContent='3D unavailable. All station content remains accessible.';});return r;}
function lighting(scene){scene.add(new THREE.HemisphereLight(0xf3ffe4,0x35402b,2.2));const key=new THREE.DirectionalLight(0xffefda,4.8);key.position.set(3,6,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-4,right:4,top:5,bottom:-4});key.shadow.normalBias=.03;scene.add(key);const fill=new THREE.DirectionalLight(0xb5f1ed,2);fill.position.set(-4,3,-3);scene.add(fill);const rim=new THREE.DirectionalLight(0xff8640,1.5);rim.position.set(4,2,-3);scene.add(rim);}
function setupArm(){const r=renderer(hero,'Procedural six-axis industrial robot arm. HMI controls below adjust its joints.');const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,60);camera.position.set(5.3,3.55,6.5);camera.lookAt(.5,1.15,0);lighting(scene);const robot=createRobot();scene.add(robot.robot);const floor=mesh(scene,new THREE.CylinderGeometry(2.55,2.55,.12,72),new THREE.MeshStandardMaterial({color:0x293024,metalness:.45,roughness:.55}),0,-.08,0);floor.receiveShadow=true;const grid=new THREE.GridHelper(5.3,18,0x788462,0x414b35);grid.position.y=-.006;scene.add(grid);const ring=mesh(scene,new THREE.TorusGeometry(2.45,.012,8,90),new THREE.MeshBasicMaterial({color:0xff8a45}),0,.005,0);ring.rotation.x=Math.PI/2;const smallboxmat=new THREE.MeshStandardMaterial({color:0xb8c7a5,roughness:.55,metalness:.3});box(scene,.35,.35,.35,smallboxmat,1.75,.17,.65);let pose={base:20,shoulder:-20,elbow:-70,wrist:0,pitch:0,roll:0,grip:.6};return{renderer:r,scene,camera,robot,pose,view:hero};}
function setupStation(){const r=renderer(stationView,'Procedural 3D concept illustration for the active internship station.');const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(37,1,.1,60);camera.position.set(4.3,2.5,6.5);camera.lookAt(0,.15,0);lighting(scene);const models=createStations();models.forEach((m,i)=>{m.group.visible=i===activeStation;scene.add(m.group);});return{renderer:r,scene,camera,models,view:stationView};}
function resize(obj){if(!obj||obj.renderer.userLost)return;const w=obj.view.clientWidth,h=obj.view.clientHeight;if(w<1||h<1)return;obj.camera.aspect=w/h;obj.camera.zoom=obj===arm?Math.min(1,w/h*1.25):Math.min(1.12,w/h*1.25);obj.camera.updateProjectionMatrix();obj.renderer.setSize(w,h,false);obj.renderer.render(obj.scene,obj.camera);}
function setQuality(){quality=state.quality;[arm,station].forEach(o=>{if(!o)return;o.renderer.setPixelRatio(Math.min(devicePixelRatio||1,quality==='lite'?1.15:2));o.renderer.shadowMap.enabled=quality==='high';resize(o);});}
function updateArm(dt){if(!arm)return;if(state.estop)return;if(state.manual){Object.assign(arm.pose,state.pose);arm.robot.setPose(arm.pose);return;}if(!state.running||!state.ambient)return;const pointer=state.pointer;let target;if(pointer.active&&arm.view===hero){const x=1.3+pointer.x*.55,y=1.65+pointer.y*.55,z=-pointer.x*.75;const dx=Math.hypot(x,z),dy=y-.9;const cosine=THREE.MathUtils.clamp((dx*dx+dy*dy-1.5**2-1.28**2)/(2*1.5*1.28),-.95,.95);const q2=-Math.acos(cosine),q1=Math.atan2(dy,dx)-Math.atan2(1.28*Math.sin(q2),1.5+1.28*Math.cos(q2));target={base:THREE.MathUtils.radToDeg(Math.atan2(-z,x)),shoulder:THREE.MathUtils.radToDeg(q1-Math.PI/2),elbow:THREE.MathUtils.radToDeg(q2)};}else target={base:20+Math.sin(clock*.35)*20+state.scroll*12,shoulder:-20+Math.sin(clock*.55)*9,elbow:-70+Math.sin(clock*.55+1.5)*15};const blend=1-Math.exp(-dt*4.5);for(const k of ['base','shoulder','elbow'])arm.pose[k]=THREE.MathUtils.lerp(arm.pose[k],target[k],blend);arm.pose.wrist=Math.sin(clock*.4)*22;arm.pose.pitch=Math.sin(clock*.3)*12;arm.pose.roll=Math.sin(clock*.5)*28;arm.pose.grip=.5+.4*Math.sin(clock*.7);arm.robot.setPose(arm.pose);}
let lastRender=0;
function frame(now){frameId=0;if(document.hidden||$('dialog[open]')){last=0;return;}const dt=last?Math.min(.06,(now-last)/1000):.016;last=now;const renderNow=quality==='high'||now-lastRender>=30;if(state.ambient&&!state.estop)clock+=dt*(.3+state.speed*1.7);if(renderNow){lastRender=now;if(arm&&(heroVisible||previewVisible)&&!arm.renderer.userLost){updateArm(dt);arm.renderer.render(arm.scene,arm.camera);if(state.running&&state.ambient&&!state.estop)$('#conveyor-view').style.setProperty('--belt-offset',(clock*10%36)+'px');}if(station&&stationVisible&&!station.renderer.userLost){if(state.ambient&&!state.estop)station.models[activeStation].animate(clock,state.wind);station.renderer.render(station.scene,station.camera);}if(state.quality==='high'&&dt>.027)slow++;frames++;if(frames===180&&slow>85){state.quality='lite';$('#quality').value='lite';setQuality();}}
 if((heroVisible||previewVisible||stationVisible)&&state.ambient&&!state.estop){frameId=requestAnimationFrame(frame);}else last=0;
}
function request(){if(!frameId&&!document.hidden)frameId=requestAnimationFrame(frame);}
function moveArmView(){if(!arm)return;const target=previewVisible?preview:hero;if(target!==arm.view){arm.view.classList.remove('scene-ready');target.append(arm.renderer.domElement);target.classList.add('scene-ready');arm.view=target;resize(arm);}request();}
try{arm=setupArm();$('#machine-controls').disabled=false;$('#robot-state').textContent='Six-axis procedural robot · interactive';$('#hmi-caption').textContent='Robot + conveyor demo';}catch(error){console.warn('Robot WebGL fallback:',error.message);$('#robot-state').textContent='Static concept view · WebGL unavailable';$('#hmi-state').textContent='OFFLINE';document.body.classList.add('webgl-failed');$('.stage-foot .mono').textContent='Static view of the procedural model';$('#control-preview > .mono').textContent='ROBOT / STATIC CONCEPT VIEW';}
const resizeObserver=new ResizeObserver(()=>{resize(arm);resize(station);request();});[hero,preview,stationView].forEach(v=>resizeObserver.observe(v));
const observer=new IntersectionObserver(entries=>{for(const e of entries){if(e.target===hero)heroVisible=e.isIntersecting;if(e.target===preview)previewVisible=e.isIntersecting;if(e.target===stationView){stationVisible=e.isIntersecting;if(stationVisible&&!station&&!stationAttempted){stationAttempted=true;try{station=setupStation();resize(station);}catch(error){console.warn('Station WebGL fallback:',error.message);document.body.classList.add('webgl-station-failed');$('#station-illustration').textContent='Static concept view. All project information remains accessible.';}}}}moveArmView();request();},{threshold:.03});[hero,preview,stationView].forEach(v=>observer.observe(v));
addEventListener('station:change',e=>{activeStation=e.detail;if(station){station.models.forEach((m,i)=>m.group.visible=i===activeStation);station.models[activeStation].animate(clock,state.wind);}request();});
// site.js selects the current station before this module has finished loading.
const selected=document.querySelector('.station.is-active');if(selected)activeStation=Number(selected.dataset.station);
addEventListener('machine:quality',()=>{setQuality();request();});addEventListener('machine:change',()=>{if(state.manual&&!state.estop)updateArm(0);request();});addEventListener('portfolio:scroll',request);addEventListener('portfolio:dialog',request);document.addEventListener('visibilitychange',()=>{last=0;request();});
resize(arm);request();
