(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const base='/ShreeChoudhari/';
const low=matchMedia('(max-width: 760px)').matches || (navigator.deviceMemory && navigator.deviceMemory<=4) || (navigator.hardwareConcurrency && navigator.hardwareConcurrency<=4);
const state=window.portfolioState={running:!reduced.matches,estop:false,manual:false,ambient:!reduced.matches,speed:.4,wind:8,quality:low?'lite':'high',pose:{base:20,shoulder:-20,elbow:-70},pointer:{x:0,y:0,active:false},scroll:0};
const event=name=>dispatchEvent(new CustomEvent(name));
let toastTimer;function toast(text){const el=$('#toast');el.textContent=text;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,3000);}window.portfolioToast=toast;
const menu=$('.menu-button');menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));$('nav').classList.toggle('open',open);});$$('nav a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');$('nav').classList.remove('open');}));
$$('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);toast('Copied to clipboard');}catch{toast('Copy: '+b.dataset.copy);}}));
const filters=$$('[data-filter]');
function filter(category){const c=['all','corporate','academic'].includes(category)?category:'all';let n=0;$$('.project-card').forEach(card=>{card.hidden=c!=='all'&&card.dataset.category!==c;if(!card.hidden)n++;const a=card.querySelector('.project-open');const u=new URL(a.href);u.searchParams.set('from',c);a.href=u.href;});filters.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===c)));if($('#project-count'))$('#project-count').textContent=n+' projects';event('portfolio:layout');}
if(filters.length){filter(new URLSearchParams(location.search).get('category'));filters.forEach(b=>b.addEventListener('click',()=>{filter(b.dataset.filter);const u=new URL(location.href);u.searchParams.set('category',b.dataset.filter);u.hash='selected-work';history.pushState({},'',u);}));addEventListener('popstate',()=>filter(new URLSearchParams(location.search).get('category')));}
$$('[data-back]').forEach(a=>{const from=new URLSearchParams(location.search).get('from');a.href=base+'?category='+(['all','corporate','academic'].includes(from)?from:a.dataset.back)+'#selected-work';});
const dialog=$('#speedrun-dialog'),trigger=$('#speedrun');let briefTimer;
function finishBrief(){clearTimeout(briefTimer);$$('.brief-grid [data-full-text]').forEach(p=>{if(p.dataset.fullHtml)p.innerHTML=p.dataset.fullHtml;else p.textContent=p.dataset.fullText;delete p.dataset.fullText;delete p.dataset.fullHtml;});$('#show-brief').hidden=true;$('#brief-status').textContent='Profile ready · 5 internships';}
trigger?.addEventListener('click',()=>{dialog.showModal();document.body.style.overflow='hidden';event('portfolio:dialog');const lines=$$('.brief-grid section p');if(!reduced.matches){const line=lines[0];line.dataset.fullHtml=line.innerHTML;line.dataset.fullText=line.innerText||line.textContent;const text=line.dataset.fullText;line.textContent='';let i=0;$('#brief-status').textContent='Reading profile…';$('#show-brief').hidden=false;function tick(){if(!dialog.open)return;i+=5;line.textContent=text.slice(0,i);if(i<text.length)briefTimer=setTimeout(tick,12);else finishBrief();}tick();}else finishBrief();$('#close-speedrun').focus();});
$('#show-brief')?.addEventListener('click',finishBrief);$('#close-speedrun')?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('close',()=>{finishBrief();document.body.style.overflow='';trigger.focus({preventScroll:true});event('portfolio:dialog');});dialog?.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
const boot=$('#boot');
if(boot){let seen=false;try{seen=sessionStorage.getItem('seven-stations-boot')==='1';sessionStorage.setItem('seven-stations-boot','1');}catch{}if(!seen&&!reduced.matches&&!location.hash){boot.hidden=false;const start=performance.now();let closed=false;const close=()=>{closed=true;boot.classList.add('exit');setTimeout(()=>boot.hidden=true,500);};$('#skip-boot').onclick=close;function tick(now){if(closed)return;const v=Math.min(100,Math.floor((now-start)/11));$('#boot-number').innerHTML=String(v).padStart(2,'0')+'<span>%</span>';boot.style.setProperty('--boot-progress',v+'%');$('#boot-status').textContent=v<32?'I/O CHECK... OK':v<65?'HMI... OK':v<100?'SERVO... OK':'PORTFOLIO... READY';if(v<100)requestAnimationFrame(tick);else setTimeout(close,150);}requestAnimationFrame(tick);}}
const cross=$('.cursor-cross');if(matchMedia('(hover: hover) and (pointer: fine)').matches&&!reduced.matches){document.body.classList.add('cursor-enabled');addEventListener('pointermove',e=>{cross.style.left=e.clientX+'px';cross.style.top=e.clientY+'px';cross.classList.toggle('hover',!!e.target.closest('a,button,input'));},{passive:true});document.addEventListener('mouseleave',()=>cross.style.opacity=0);document.addEventListener('mouseenter',()=>cross.style.opacity=1);}
const stationTitles=['XR TRAINING','AI TRANSLATION','WIND ENERGY','TASK MANAGEMENT','HRMS AUTOMATION','RECRUITMENT AI','PEOPLE & PURPOSE'];
const stationReadouts=['XR / TRAINING ENVIRONMENT','AI / TOKEN STREAM','VAWT / 3 kW RATED','APP / REVIEW QUEUE','FLOW / TRIGGER → APPROVAL → RECORD','AGENT / ILLUSTRATIVE SCAN','CSR / HUMAN CONNECTION'];
const stations=$$('.station');let active=-1,scrollQueued=false;
function setActive(i){if(i===active)return;active=i;stations.forEach((s,n)=>s.classList.toggle('is-active',n===i));$$('.station-nav a').forEach((a,n)=>{if(n===i)a.setAttribute('aria-current','true');else a.removeAttribute('aria-current');});$('#active-station').textContent='ST-'+String(i+1).padStart(2,'0')+' / '+stationTitles[i];$('#station-readout').textContent=stationReadouts[i];$('.station-fallback span').textContent=String(i+1).padStart(2,'0');if(!$('#station-view').classList.contains('scene-ready'))$('#station-fallback-image').src=base+'assets/station-'+(i+1)+'-fallback.svg?v=3';$('#station-illustration').textContent=document.body.classList.contains('webgl-station-failed')?'Static 3D concept view · interactive rendering unavailable.':i===5?'Synthetic CV and illustrative score. No real candidate data.':'Procedural 3D illustration. Scroll to the next station.';dispatchEvent(new CustomEvent('station:change',{detail:i}));}
function onScroll(){scrollQueued=false;if(stations.length){const line=$('.station-stream').getBoundingClientRect();const threshold=innerWidth<=800?Math.min(innerHeight*.58,350):innerHeight*.43;let i=0;stations.forEach((s,n)=>{if(s.getBoundingClientRect().top<=threshold)i=n;});setActive(i);$('.signal-line').style.setProperty('--signal-progress',String(Math.max(0,Math.min(1,(threshold-line.top)/line.height))));}state.scroll=Math.min(1,scrollY/Math.max(1,innerHeight));event('portfolio:scroll');}
addEventListener('scroll',()=>{if(!scrollQueued){scrollQueued=true;requestAnimationFrame(onScroll);}},{passive:true});addEventListener('resize',onScroll);if(stations.length)onScroll();
let audioCtx,oscillator,gain,sound=false;
function updateSound(){if(!gain||!audioCtx)return;const audible=sound&&state.running&&!state.estop&&state.ambient&&!document.hidden;gain.gain.setTargetAtTime(audible?.012:0,audioCtx.currentTime,.12);oscillator.frequency.setTargetAtTime(44+state.speed*36,audioCtx.currentTime,.15);}
function ui(){document.body.classList.toggle('alarm',state.estop);document.body.classList.toggle('motion-paused',!state.ambient||state.estop);if($('#hmi-state'))$('#hmi-state').textContent=state.estop?'E-STOP':state.running?(state.ambient?'RUN':'PAUSE'):'STOP';if($('#hmi-caption'))$('#hmi-caption').textContent=state.estop?'Reset to release alarm':state.manual?'Manual joint control':'Robot + conveyor demo';$('#motion-toggle')?.setAttribute('aria-pressed',String(!state.ambient));if($('#motion-toggle'))$('#motion-toggle').textContent=state.ambient?'Pause ambient motion':'Resume ambient motion';$$('.sliders input').forEach(el=>el.disabled=state.estop);if($('#wind'))$('#wind').disabled=state.estop;updateSound();event('machine:change');}
$('#machine-start')?.addEventListener('click',()=>{if(state.estop){toast('Press Reset to release the emergency stop.');return;}state.running=true;state.ambient=true;state.manual=false;ui();});
$('#machine-stop')?.addEventListener('click',()=>{state.running=false;ui();});
$('#machine-estop')?.addEventListener('click',()=>{state.estop=true;state.running=false;ui();});
$('#machine-reset')?.addEventListener('click',()=>{state.estop=false;state.running=false;state.manual=true;state.pose={base:20,shoulder:-20,elbow:-70};['base','shoulder','elbow'].forEach(k=>{$('#'+k).value=state.pose[k];$('#'+k+'-value').textContent=state.pose[k]+'°';});ui();});
['base','shoulder','elbow'].forEach(k=>$('#'+k)?.addEventListener('input',e=>{if(state.estop)return;state.running=false;state.manual=true;state.pose[k]=Number(e.target.value);$('#'+k+'-value').textContent=e.target.value+'°';ui();}));
$('#speed')?.addEventListener('input',e=>{state.speed=Number(e.target.value)/100;$('#speed-value').textContent=e.target.value+'%';ui();});
$('#motion-toggle')?.addEventListener('click',()=>{state.ambient=!state.ambient;ui();});
$('#sound-toggle')?.addEventListener('click',async()=>{try{if(!audioCtx){const Context=window.AudioContext||window.webkitAudioContext;if(!Context)throw Error('Audio unavailable');audioCtx=new Context();oscillator=audioCtx.createOscillator();oscillator.type='sine';gain=audioCtx.createGain();gain.gain.value=0;oscillator.connect(gain).connect(audioCtx.destination);oscillator.start();}await audioCtx.resume();sound=!sound;$('#sound-toggle').textContent=sound?'Sound on':'Sound off';$('#sound-toggle').setAttribute('aria-pressed',String(sound));updateSound();}catch{toast('Sound is unavailable in this browser.');}});
const quality=$('#quality');if(quality){quality.value=state.quality;quality.addEventListener('change',()=>{state.quality=quality.value;event('machine:quality');});}
$('#wind')?.addEventListener('input',e=>{state.wind=Number(e.target.value);$('#wind-value').textContent=state.wind+' m/s';const power=Math.min(3,3*Math.pow(state.wind/12,3));$('#wind-power').innerHTML=power.toFixed(2)+' <small>kW</small>';event('machine:change');});
reduced.addEventListener('change',e=>{if(e.matches){state.ambient=false;state.running=false;document.body.classList.remove('cursor-enabled');}ui();event('portfolio:reduced-motion');});
document.addEventListener('visibilitychange',updateSound);if($('#hmi'))ui();
const rob=$('#robot-view');rob?.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const r=rob.getBoundingClientRect();state.pointer={x:((e.clientX-r.left)/r.width-.5)*2,y:(.5-(e.clientY-r.top)/r.height)*2,active:true};});rob?.addEventListener('pointerleave',()=>state.pointer.active=false);
// Core content and controls do not depend on remote motion libraries.
if(rob){import(base+'js/scenes.js?v=stations3').catch(()=>{$('#robot-state').textContent='3D unavailable · all project content remains accessible';$('#hmi-state').textContent='OFFLINE';document.body.classList.add('webgl-failed');});}
if(!reduced.matches)import(base+'js/motion.js?v=stations3').catch(()=>{});
function restoreHash(){if(!location.hash)return;const el=document.getElementById(decodeURIComponent(location.hash.slice(1)));el?.scrollIntoView({behavior:'instant',block:'start'});}
addEventListener('pageshow',()=>{if(location.hash)requestAnimationFrame(()=>requestAnimationFrame(restoreHash));});
})();
