import * as T from 'three';
export const orange=new T.MeshStandardMaterial({color:0xff8a45,metalness:.55,roughness:.32});
const dark=new T.MeshStandardMaterial({color:0x30362e,metalness:.65,roughness:.4});
const steel=new T.MeshStandardMaterial({color:0xc8d1be,metalness:.78,roughness:.25});
const black=new T.MeshStandardMaterial({color:0x101711,metalness:.15,roughness:.45});
const glow=new T.MeshStandardMaterial({color:0x85e8df,emissive:0x66d8d6,emissiveIntensity:.8,metalness:.4,roughness:.3});
export function mesh(parent,geo,mat,x=0,y=0,z=0){const m=new T.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
export function box(g,w,h,d,m,x=0,y=0,z=0){return mesh(g,new T.BoxGeometry(w,h,d),m,x,y,z);}
export function cyl(g,r,h,m,x=0,y=0,z=0){return mesh(g,new T.CylinderGeometry(r,r,h,32),m,x,y,z);}
function sphere(g,r,m,x=0,y=0,z=0){return mesh(g,new T.SphereGeometry(r,20,14),m,x,y,z);}
function line(g,points,color=0x77cccc){const m=new T.Line(new T.BufferGeometry().setFromPoints(points.map(p=>new T.Vector3(...p))),new T.LineBasicMaterial({color,transparent:true,opacity:.45}));g.add(m);return m;}
function label(g,text,w=2.3,h=.65,x=0,y=0,z=0,color='#91e6dc'){
 const c=document.createElement('canvas');c.width=640;c.height=160;const ctx=c.getContext('2d');ctx.fillStyle='#141d17';ctx.fillRect(0,0,640,160);ctx.strokeStyle='#526348';ctx.lineWidth=3;ctx.strokeRect(2,2,636,156);ctx.fillStyle=color;ctx.font='500 40px monospace';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,320,80);const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;const mat=new T.MeshBasicMaterial({map:texture,transparent:false});return mesh(g,new T.PlaneGeometry(w,h),mat,x,y,z);
}
function platform(g){cyl(g,1.75,.1,dark,0,-1.5,0);const r=mesh(g,new T.TorusGeometry(1.72,.018,8,80),glow,0,-1.44,0);r.rotation.x=Math.PI/2;}
function xr(){const g=new T.Group();platform(g);const body=new T.Group();g.add(body);box(body,1.9,.83,.65,steel,0,.45,0);const visor=box(body,1.78,.68,.12,black,0,.47,.38);for(const x of [-.58,0,.58]){const lens=cyl(body,.115,.04,glow,x,.48,.47);lens.rotation.x=Math.PI/2;}const strap=mesh(body,new T.TorusGeometry(.68,.09,10,40,Math.PI),dark,0,.51,-.05);strap.rotation.x=Math.PI/2;strap.rotation.z=Math.PI;const hands=[];[-1,1].forEach(s=>{const a=new T.Group();a.position.set(s*1.25,-.65,.4);a.rotation.z=s*.35;body.add(a);mesh(a,new T.CapsuleGeometry(.12,.42,5,16),steel);sphere(a,.23,dark,0,.3,0);const ring=mesh(a,new T.TorusGeometry(.28,.04,8,32),glow,0,.4,0);ring.rotation.x=.6;hands.push(a);});const p=label(g,'XR / TRAINING VIEWPORT',2.6,.55,0,1.5,-.7);return{group:g,animate:t=>{body.position.y=Math.sin(t*.65)*.09;body.rotation.y=Math.sin(t*.3)*.2;p.rotation.y=Math.sin(t*.3)*.1;}};}
function llm(){const g=new T.Group();platform(g);const nodes=[];for(let layer=0;layer<3;layer++){for(let i=0;i<4;i++){const p=[(layer-1)*1.15,(i-1.5)*.55,Math.sin(i*1.6+layer)*.35];nodes.push(sphere(g,.12,layer===1?orange:glow,...p));}}
 const links=[];for(let a=0;a<8;a++)for(let b=0;b<4;b++){const from=nodes[a].position,to=nodes[(Math.floor(a/4)+1)*4+b].position;line(g,[from.toArray(),to.toArray()]);if(b===a%4)links.push([from,to]);}
 const pulses=links.map(()=>sphere(g,.045,glow));let word='';const l=label(g,'LANGUAGE / TOKENS',2.9,.6,0,1.7,0);return{group:g,animate:t=>{nodes.forEach((n,i)=>{n.scale.setScalar(1+.2*Math.sin(t*2+i));});pulses.forEach((p,i)=>p.position.lerpVectors(...links[i],(t*.3+i*.12)%1));const w=['EN / FR / AR','INPUT > TOKENS','TOKENS > OUTPUT'][Math.floor(t/3)%3];if(w!==word){word=w;const c=l.material.map.image,ctx=c.getContext('2d');ctx.fillStyle='#141d17';ctx.fillRect(3,3,634,154);ctx.fillStyle='#91e6dc';ctx.fillText(w,320,80);l.material.map.needsUpdate=true;}}};}
function wind(){const g=new T.Group();platform(g);cyl(g,.12,3.3,steel,0,.2,0);cyl(g,.42,.5,dark,0,-1.15,0);const rotor=new T.Group();g.add(rotor);for(const y of [-.85,1.45]){cyl(rotor,.21,.1,steel,0,y,0);for(let j=0;j<3;j++){const arm=box(rotor,1.95,.035,.07,steel,0,y,0);arm.rotation.y=j*Math.PI/3;}}
 for(let b=0;b<3;b++){const verts=[],inds=[],n=44;for(let i=0;i<=n;i++){const v=i/n,y=-.85+v*2.3,a=b*Math.PI*2/3+v*Math.PI*.9;for(let edge=0;edge<2;edge++){const da=(edge-.5)*.5;verts.push(Math.cos(a+da)*.9,y,Math.sin(a+da)*.9);}}for(let i=0;i<n;i++){const k=i*2;inds.push(k,k+1,k+2,k+1,k+3,k+2);}const geom=new T.BufferGeometry();geom.setAttribute('position',new T.Float32BufferAttribute(verts,3));geom.setIndex(inds);geom.computeVertexNormals();const material=orange.clone();material.side=T.DoubleSide;mesh(rotor,geom,material);}
 const ring=mesh(g,new T.TorusGeometry(2,.012,8,100),new T.MeshBasicMaterial({color:0x77dddd,transparent:true,opacity:.5}),0,0,0);ring.rotation.x=Math.PI/2;const flows=[];for(let i=0;i<12;i++){const f=box(g,.34,.012,.012,glow,-2.5,(i%4)*.55-.7,Math.floor(i/4)*.6-.6);flows.push(f);}let angle=0,prev=0;return{group:g,animate:(t,wind=8)=>{const dt=Math.min(.08,Math.max(0,t-prev));prev=t;angle+=dt*wind*.22;rotor.rotation.y=angle;flows.forEach((f,i)=>{f.position.x=-2.5+((t*wind*.25+i*.43)%5);f.visible=wind>0;});}};}
function tasks(){const g=new T.Group();platform(g);const board=new T.Group();g.add(board);box(board,3.3,2.3,.12,dark,0,.2,0);for(let i=0;i<3;i++){label(board,['QUEUED','ACTIVE','REVIEW'][i],.96,.29,(i-1)*1.05,1.05,.08);box(board,.018,1.7,.02,steel,(i-1.5)*1.05,.05,.09);}const cards=[];for(let i=0;i<5;i++){const c=new T.Group();board.add(c);box(c,.82,.34,.08,i===0?orange:steel);box(c,.4,.022,.01,dark,-.12,.04,.05);box(c,.6,.015,.01,dark,0,-.055,.05);c.position.set((i%3-1)*1.05,.55-Math.floor(i/3)*.58,.16);cards.push(c);}return{group:g,animate:t=>{cards[0].position.x=-1.05+((Math.sin(t*.6)+1)/2)*2.1;cards[0].position.z=.24;board.rotation.y=Math.sin(t*.25)*.12;}};}
function flow(){const g=new T.Group();platform(g);const ns=[[-1.2,.75,0],[0,0,.35],[1.2,-.75,0]];const pulse=sphere(g,.085,glow);ns.forEach((p,i)=>{box(g,.85,.65,.25,i===1?orange:dark,...p);label(g,['TRIGGER','APPROVE','RECORD'][i],.82,.27,p[0],p[1],p[2]+.15);if(i<2)line(g,[p,[p[0],ns[i+1][1],p[2]],ns[i+1]],0x91e6dc);});return{group:g,animate:t=>{const q=(t*.5)%2,i=Math.floor(q);pulse.position.lerpVectors(new T.Vector3(...ns[i]),new T.Vector3(...ns[i+1]),q-i);}};}
function agent(){const g=new T.Group();platform(g);const cv=new T.Group();g.add(cv);box(cv,1.8,2.4,.1,steel,-.35,.15,0);sphere(cv,.2,dark,-.7,.85,.1);for(let i=0;i<7;i++)box(cv,i<2?.65:1.35,.035,.02,dark,i<2?0:-.35,.95-i*.24,.07);const scan=box(cv,2.03,.025,.18,glow,-.35,0,.15);label(g,'DEMO CV',1.35,.36,-.35,1.65,0);const core=new T.Group();core.position.set(1.2,.4,.2);g.add(core);mesh(core,new T.IcosahedronGeometry(.36,1),orange);const ring=mesh(core,new T.TorusGeometry(.6,.015,8,50),glow);label(g,'ILLUSTRATION / 82',2.4,.45,.25,-1.05,.35);return{group:g,animate:t=>{scan.position.y=.15+Math.sin(t*1.1)*1.1;core.rotation.y=t*.35;ring.rotation.x=t*.2;}};}
function csr(){const g=new T.Group();platform(g);for(let i=0;i<5;i++){const a=(i/5)*Math.PI*2,person=new T.Group();person.position.set(Math.cos(a)*1.1,-.65,Math.sin(a)*.6);g.add(person);mesh(person,new T.CapsuleGeometry(.16,.36,4,12),i===0?orange:steel,0,.2,0);sphere(person,.16,i===0?orange:steel,0,.72,0);box(person,.32,.17,.22,dark,0,-.2,0);}const globe=new T.Group();globe.position.y=.85;g.add(globe);sphere(globe,.48,dark);for(let i=0;i<3;i++){const r=mesh(globe,new T.TorusGeometry(.51,.013,8,40),glow);r.rotation.y=i*Math.PI/3;}const r=mesh(globe,new T.TorusGeometry(.51,.013,8,40),glow);r.rotation.x=Math.PI/2;return{group:g,animate:t=>globe.rotation.y=t*.12};}
export function createStations(){return[xr(),llm(),wind(),tasks(),flow(),agent(),csr()];}
